### ISSUE TITLE
是否能提供比赛版本的pdf2txt工具，现在的pdf2txt工具转化的结果与当时比赛直接提供的alltxt里的txt并不匹配

### ISSUE THREAD

**Issue by cloudyskyy** [MetaGLM/FinGLM#10]
现在提供的pdf2txt工具转化出来的txt和当时比赛直接提供的alltxt里的txt格式不一样，这会导致复现决赛队伍代码时会出很多错，比如抽不出三大表中的数值项。导致我们必须使用当时比赛提供的all txt来复现代码。可问题是这样会导致难以实际运用。所以能否提供一下当时比赛提供的alltxt对应版本的pdf2txt工具呢？

**Comment by dictmap** [comment]
table_settings = {"intersection_x_tolerance": 1}
table = first_page.extract_table(table_settings)

**Comment by dictmap** [comment]
比赛提供了两版txt，区别主要在上面的代码，可以试一下~~~

**Comment by cloudyskyy** [comment]
好的谢谢

**Comment by Xu-Wave** [comment]
<img width="794" alt="image" src="https://github.com/MetaGLM/FinGLM/assets/52534943/e4508bf6-b569-4827-8cee-b9f187f5f17f">
63行和64行 二选一 对吗~
决赛大家用的哪一行的呀？
@dictmap
