### ISSUE TITLE
馒头科技项目怎么能运行起来

### ISSUE THREAD

**Issue by Young1993** [MetaGLM/FinGLM#13]
您好，我运行馒头科技的main.py 但是呢，它里面建的几张表格都没看懂，如下所示
    
path = {
        'basic_info': os.path.join(cfg.DATA_PATH, 'pdf_docs', key, 'basic_info.txt'),
        'employee_info': os.path.join(cfg.DATA_PATH, 'pdf_docs', key, 'employee_info.txt'),
        'cbs_info': os.path.join(cfg.DATA_PATH, 'pdf_docs', key, 'cbs_info.txt'),
        'cscf_info': os.path.join(cfg.DATA_PATH, 'pdf_docs', key, 'cscf_info.txt'),
        'cis_info': os.path.join(cfg.DATA_PATH, 'pdf_docs', key, 'cis_info.txt'),
        'dev_info': os.path.join(cfg.DATA_PATH, 'pdf_docs', key, 'dev_info.txt'),
    }

应该怎么获得这几张表？

**Comment by AIXiaoBaiDemon** [comment]
我下载了原始的pdf文件，但是没有pdf_info.json文件，想请问一下该文件如何生成，谢谢~~
