### ISSUE TITLE
感谢分享～

### ISSUE THREAD

**Issue by Juicechen95** [MetaGLM/FinGLM#14]
我想表达一下我对各位开源贡献者的感谢！

**Comment by jiawei243** [comment]
收到，有哪些帮助到了您？

**Comment by Juicechen95** [comment]
先看了馒头科技的技术文档，非常详细，收获较多～
如果有代码执行指令指引就更好了～


感谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jiawei ***@***.***&gt;
发送时间: 2023年10月26日 16:26
收件人: MetaGLM/FinGLM ***@***.***&gt;
抄送: Orange Jiang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MetaGLM/FinGLM] 感谢分享～ (Issue #14)





 
收到，有哪些帮助到了您？
