### ISSUE TITLE
finglm_all/prepare_data目录下的industry文件是怎么获取的

### ISSUE THREAD

**Issue by mfxss** [MetaGLM/FinGLM#18]
看了一下脚本，先用pdf2txt转成txt文件，然后用cut_table_base.py、cut_table_fin.py、cut_table_others.py三个脚本生成big_data1、big_data2、big_data3三个文件，最后用data_process.py脚本合并，这个时候多出了一个industry.xlsx文件。请问industry.xlsx文件是通过哪个脚本生成的？

**Comment by KLinnnnnn** [comment]
industry.xlsx是通过公司找到的该公司的申万行业，这个是通过自有库或者其他渠道映射出来的，考虑到同学们可能会缺失这部分数据，所以直接给出来了
