### ISSUE TITLE
finglm_all/prepare_data/data_process.py报错：KeyError: '格式化企业名称'（line 70，company_name = row['格式化企业名称']）

### ISSUE THREAD

**Issue by mouju** [MetaGLM/FinGLM#20]
已有big_data123，industry

**Comment by KLinnnnnn** [comment]
“格式化企业名称字段”就是big_data123里面文件名称中的公司全称，例如：2022-12-31__棕榈生态城镇发展股份有限公司__002431__2022年__年度报告.txt 格式化企业名称就是棕榈生态城镇发展股份有限公司
