### ISSUE TITLE
表格的关键词怎么获得的？

### ISSUE THREAD

**Issue by msn199959** [MetaGLM/FinGLM#21]
比如code/finglm_all/prepare_data/cut_table_fin.py中
list2 = [
    '货币资金', '结算备付金', '拆出资金', '交易性金融资产', '以公允价值计量且其变动计入当期损益的金融资产', '衍生金融资产', '应收票据',
    '应收账款', '应收款项融资', '预付款项', '应收保费', '应收分保账款', '应收分保合同准备金', '其他应收款', '应收利息', '应收股利',
    '买入返售金融资产', '存货', '合同资产', '持有待售资产', '一年内到期的非流动资产', '其他流动资产',
    '流动资产合计',
    '发放贷款和垫款', '债权投资', '可供出售金融资产', '其他债权投资', '持有至到期投资', '长期应收款', '长期股权投资',
    '其他权益工具投资', '其他非流动金融资产', '投资性房地产', '固定资产', '在建工程', '生产性生物资产', '油气资产', '使用权资产',
    '无形资产', '开发支出', '商誉', '长期待摊费用', '递延所得税资产', '其他非流动资产',
    '非流动资产合计', '资产总计',
    '短期借款', '向中央银行借款', '拆入资金', '交易性金融负债', '以公允价值计量且其变动计入当期损益的金融负债', '衍生金融负债'}
这些专业术语是怎么获得的呢？

**Comment by dictmap** [comment]
这些是财务报表中的科目
