### ISSUE TITLE
请问南哪都队的答案生成模块中，标题向量化这一步对应的是哪个文件

### ISSUE THREAD

**Issue by mouju** [MetaGLM/FinGLM#22]
![image](https://github.com/MetaGLM/FinGLM/assets/48321816/5b6c51b6-b79a-4d6b-86ce-52bbafed9b94)

**Comment by mouju** [comment]
是query_company.py吗？如果是的话，retrieved_info.jsonl是怎么生成的呀？

**Comment by jiawei243** [comment]
这里：glm_components/query/document_retrieval/new_format_document.py
