### ISSUE TITLE
请问南哪都队finetune/table_qa/classifier.py文件里面的finance_features_alias、finance_compute_alias、finance_compute_feaures这些字是怎么提取出来的？

### ISSUE THREAD

**Issue by YangLei6** [MetaGLM/FinGLM#26]
finance_features_alias = {
    "研发费用": ["研发经费", "企业研发经费", '花费在研发上的费用'],
    # '收回投资所得的现金': ['收回投资所得现金'],
    '净利润': ['利润', '净利润总额'],
    '利息支出': ['支出的利息'],
    '归属于母公司所有者的净利润': ['归属母公司所有者净利润', '归属母公司净利润', '归属母公司所有者的净利润', '归属于母公司股东的净利润'],
    '归属于母公司所有者权益合计': ['归属于母公司所有者权益（或股东权益）合计', '归属于母公司的所有者权益', '归属于母公司的所有者权益', '归属于母公司所有者权益'],
    '资产合计': ['总资产', '资产总额', '资产总计', '资产总金额'],
    '负债合计': ['总负债', '负债总额', '负债总金额'],
    '收回投资收到的现金': [
        '收到的投资回收现金', '收回投资所得现金', '收回投资所得的现金','收回投资所收到的现金', 
        '收回投资所获得的现金', '收回投资所得到的现金', '收回的投资所得到的现金','收回的投资所得现金', 
        '收回的投资收入', '收回的投资收到的现金', '收回的投资现金', '收到的投资收回的现金'
    ],
    '无形资产': ['无形资产价值'],
    '每股净资产': ['每股净资产价值', '每股的净资产'],
    '流动负债合计': ['流动负债', '流动负债总计'],
    '流动资产合计': ['流动资产', '流动资产总计'],
    '期末现金及现金等价物余额': ['现金及现金等价物余额','期末的现金及现金等价物余额', '现金及现金等价物'],
    '经营活动产生的现金流量': ['经营现金流量'],
    '应付职工薪酬': ['应付的职工薪酬', '需支付的职工薪酬', '职工薪酬'],
    '对联营企业和合营企业的投资收益': ['对其联营企业和合营企业的投资收益'],
    '税金及附加': ['营业税金及附加费用', '营业税金及附加'],
    "固定资产": ['固定资产总额'],
    '非流动负债合计': ['非流动负债', '非流动负债总计'],
    '非流动资产合计': ['非流动资产'],
    '每股经营现金流量': ['每股的经营现金流量'],
    '综合收益': ['综合收益总额', '综合收益总计'],
    '每股收益': ['基本每股收益'],
    '股本': ['实收资本', '总股数'],
    '其他综合收益': ['他综合收益'],
    '所有者权益合计': ['所有者权益总计', '股东权益合计', '净资产'],
    '货币资金': ['货币总额', '货币']
}

finance_compute_alias = {
    "企业研发经费占费用比例": ["企业研发经费占费用的比例", "企业研发经费占总费用的比例", '企业研发经费在总费用中的比例', '研发经费占费用的比例', '研发经费占费用比例', 
                    '研发费用占总费用的比例', '研发费用占总费用的比值', '研发费用占总费用比例', '企业研发费用占总费用比例'],
    "企业研发经费与营业收入比值": ['企业研发经费与营业收入比值', '企业研发经费与营业收入的比值', '研发经费与营业收入的比值', '研发经费与营业收入比值'],
    "企业研发经费与利润比值": ['企业研发经费与利润的比值', '企业的研发经费与利润比值', '研发经费与利润的比值', '研发经费与利润比值', '企业研发经费与利润之比'],
    '投资收益占营业收入比率': ['投资收益占营业收入的比率', '投资收益占营业收入的比例', '投资收益占营业收入比例'],
    '三费比重': ['三费（销售费用、管理费用和财务费用）占比', '三费销售费用、管理费用和财务费用占比', "三费占比"],
}

**Comment by Cavary** [comment]
是人工标注了少量数据训练了一个抽取器，让大模型抽取的，这些内容都是大模型抽取+人工过滤的

**Comment by teal0range** [comment]
> > 是人工标注了少量数据训练了一个抽取器，让大模型抽取的，这些内容都是大模型抽取+人工过滤的
> 
> 我看开源的代码里没有这部分内容，是我没找到吗？

用简单的数据先训一个classifier，然后用table_qa/classifier_inference.py(比赛后期用的版本)或者extract_all/ptuning_inference.py(比赛前期用的版本)推理得出来的再人工规则处理就行了

**Comment by YangLei6** [comment]
> > > 是人工标注了少量数据训练了一个抽取器，让大模型抽取的，这些内容都是大模型抽取+人工过滤的
> > 
> > 
> > 我看开源的代码里没有这部分内容，是我没找到吗？
> 
> 用简单的数据先训一个classifier，然后用table_qa/classifier_inference.py(比赛后期用的版本)或者extract_all/ptuning_inference.py(比赛前期用的版本)推理得出来的再人工规则处理就行了

这些dict的关键词为啥要用classifier分类器？

**Comment by teal0range** [comment]
> > > > 是人工标注了少量数据训练了一个抽取器，让大模型抽取的，这些内容都是大模型抽取+人工过滤的
> > > 
> > > 
> > > 我看开源的代码里没有这部分内容，是我没找到吗？
> > 
> > 
> > 用简单的数据先训一个classifier，然后用table_qa/classifier_inference.py(比赛后期用的版本)或者extract_all/ptuning_inference.py(比赛前期用的版本)推理得出来的再人工规则处理就行了
> 
> 这些dict的关键词为啥要用classifier分类器？

这些关键词是用最初性能比较差的分类器抽出来的，整理成了dict，人工抽5000条工作量太大了，我们只标了少量的数据训最初的classifier
