### ISSUE TITLE
git 失败，显示没有这个仓库

### ISSUE THREAD

**Issue by JBYhjz** [MetaGLM/FinGLM#3]
git clone https://www.modelscope.cn/nsddd/nsddd_final.git
Cloning into 'nsddd_final'...
Username for 'https://www.modelscope.cn': ***
Password for 'https://JBY123@www.modelscope.cn': 
remote: The project you were looking for could not be found or you don't have permission to view it.
fatal: repository 'https://www.modelscope.cn/nsddd/nsddd_final.git/' not found

**Comment by jiawei243** [comment]
没有单独的nsddd仓库，都在FinGLM里面，可以：git clone https://www.modelscope.cn/finglm/FinGLM.git

**Comment by JBYhjz** [comment]
收到，谢谢你！




小何小何无可奈何
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MetaGLM/FinGLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月1日(星期天) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MetaGLM/FinGLM] git 失败，显示没有这个仓库 (Issue #3)





 
没有单独的nsddd仓库，都在FinGLM里面，可以：git clone https://www.modelscope.cn/finglm/FinGLM.git
