### ISSUE TITLE
求公开ptuning的训练数据

### ISSUE THREAD

**Issue by nuchen** [MetaGLM/FinGLM#6]
希望大佬可以公开ptuning的数据。求求了！！

**Comment by jiawei243** [comment]
您是指哪一个项目的ptuning数据？可以更具体地描述下您的述求么？

**Comment by nuchen** [comment]
> 您是指哪一个项目的ptuning数据？可以更具体地描述下您的述求么？

基本上好多队伍都微调了nl2sql的模型，这部分标注的数据能公开么？另外，mantou科技微调了好多个模型，能否复现学习。

**Comment by Remu19971202** [comment]
> 您是指哪一个项目的ptuning数据？可以更具体地描述下您的述求么？

韭菜队也微调了三个模型，能否公开这部分用于微调的数据

**Comment by dictmap** [comment]
馒头科技的：FinGLM\code\馒头科技\mantoutech\ptuning，韭菜队的我们更新一下。
