### ISSUE TITLE
运行finalglm_all/prepare_data/data_process.py出错

### ISSUE THREAD

**Issue by anyuese** [MetaGLM/FinGLM#8]
raise KeyError(key) from error
KeyError: '申万行业'，

依次运行了cut_table_base cut_table_fin cut_table_others,然后执行data_process的时候出错了

**Comment by dictmap** [comment]
我们增加一下历史的行业的数据 有个申万行业的表 如果将来使用需要及时更新

**Comment by dictmap** [comment]
> raise KeyError(key) from error KeyError: '申万行业'，
> 
> 依次运行了cut_table_base cut_table_fin cut_table_others,然后执行data_process的时候出错了

问题已处理，感谢反馈
